name = "SynapseClient"
uuid = "bcb84a12-78c7-11e9-04c6-8933c0472cec"
authors = ["Rasmus Henningsson <rasmus.henningsson@gmail.com>"]
version = "0.2.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
